version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.119.0"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo 
  post_build:
    commands:
      - aws s3 sync --delete public s3://hugo-test-serve-bucker/?region=eu-west-2
      - echo Build completed on `date`